### ISSUE TITLE
How to solve simple linear equations?

### ISSUE THREAD

**Issue by thalisvilela** [albertodev01/equations#37]
I'm trying to solve some simple equations like "0.15*(183-y)+0.3*y=0.2*183" is it possible to accomplish using this library?

**Comment by albertodev01** [comment]
Yes you can! 😄 

 1. Rewrite it as `0.15*(183-y)+0.3*x-0.2183`
 2. Use a root finding algorithm represented by `Newton`, `Bisection` or any other methods

We don't provide a direct way to solve that equation. You need a root finding algorithm. Check [here](https://github.com/albertodev01/equations#nonlinear-equations) 🙂

**Comment by thalisvilela** [comment]
I'm getting an exeption: ` ExpressionParserException: The given expression cannot be parsed! Make sure that all operators are supported. Make also sure that the product of two values explicitly has the '*' symbol.` The expression i'm passing: (0.15*(183-y)+0.3*y)-36.6
`var equacao = Newton(function: expression, x0: -1);`

**Comment by albertodev01** [comment]
You have to use `x` instead of `y` 🙂

**Comment by thalisvilela** [comment]
Thank you very much sir! I ended up simplifying the whole equation and doing regular math. But just so you know, i looked every where, and there is no library for evaluating and solving simple equations in Dart.  :-)
