### ISSUE TITLE
inverse method bug for big matrix

### ISSUE THREAD

**Issue by geopardaz** [albertodev01/equations#42]
I used the inverse method for the 12*12 matrix and the result was wrong.
also, I checked this method with Matlab and Matlab worked correctly. but this method return NaN values
I/flutter (31573): [-1.0, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, -1.0, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, -1.0, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, 0.0, NaN, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, -2.0, NaN, NaN]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, -2.0, -0.0]
I/flutter (31573): [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, -0.0, -2.0]

**Comment by albertodev01** [comment]
Hello! Thank you for opening this issue 😄 

---

You haven't provided enough information to me to solve this issue though.

 - Which input did you pass to the function?
 - How can I reproduce the bug?
 - Are you using small numbers that cause overflow errori?
