### ISSUE TITLE
how to solve the equation of the line "Ax + By + C = 0" in this library

### ISSUE THREAD

**Issue by insinfo** [albertodev01/equations#43]
how to solve the equation of the line "y = (-C - Ax) / B" in this library

```dart
var A = 1.3333333333333333;
var B = -1;
var C = 0.3333333333333335;

//y = (-C - Ax) / B
//Y = (-0.3333333333333335 - 1.3333333333333333 * X) / -1

```

**Comment by albertodev01** [comment]
Hello 🙂 

The simplest way is to use the `Linear` class, because you're trying to solve a linear equation. Your input

> Y = (-0.3333333333333335 - 1.3333333333333333 * X) / -1

is the same as

> Y = 0.3333333333333335 + 1.3333333333333333 * X

which can be solved with

```dart
final linear = Linear.realEquation(
  a: 1.3333333333333333,
  b: 0.3333333333333335,
);
```
