### ISSUE TITLE
Support muliple-variables in the non-linear methods (i.e. system of non-linear equations)

### ISSUE THREAD

**Issue by aloncatz** [albertodev01/equations#50]
I wanted to use the library to solve a system of 3 quadratic equations using Newton method, but it looks like the non-linear solvers only support single variable equations

**Comment by albertodev01** [comment]
@aloncatz thank you for opening this issue!

Yes, currently systems only work for linear equations. When I'll have enough time, I'd love to add support for nonlinear ones too
