### ISSUE TITLE
Cubic polynomial exception

### ISSUE THREAD

**Issue by hovkaren** [albertodev01/equations#52]
Get roots for this cubic polynomial occurred exception

`f(x) = x^3-1`

`ComplexException (ComplexException: The reciprocal of zero is undefined.)`

**Comment by albertodev01** [comment]
Hello! I am going to fix this in the next `5.1.0` version

**Comment by albertodev01** [comment]
Fixed here: https://github.com/albertodev01/equations/pull/55
